ipld/js-ipld

- test/ipld-tests.js
I created a new block called `across linked objects`,
inside this block there is another block `where links are multihashes`,
since in my view links could also be paths e.g.`{name: {@link: /hash/person/name}}` and I expect `where links are paths` to happen soon (I can just remove it for now)
The tests are not passing:
(my reference spec is both the ipld one and my attempt for [ip-paths](https://github.com/nicola/interplanetary-paths))
> Tests for links as hashes

- src/index.js
- test/test-ipld-dag-cbor.js
cid1
```
{
someData: 'I am 1'
}
```
cid2
```
{
someData: 'I am 3',
one: { '/': cid1 },
two: { '/': cid2 }
}
```
```
/someData == 'I am 3'
/one/someData === 'I am 1'
```
Everything is correct so far, however
```
/one must be === { someData: 'I am 1' }
// instead of
/one === { '/': cid1 },
```
---
**Update**: I fixed it in this PR
> Resolver should resolve through links

- src/index.js
- test/test-ipld-dag-cbor.js
With this PR paths in the resolver can
- start with `/`, with `./`, be `''`, or start with the name of an attribute
- contain `./`, `//`, `../`, since it will be normalized the way a path would be
> Absolute, relative paths and other edge cases

- src/index.js
Still needs new relesease of ipfs-repo and ipfs-block-service.
> Adapted to new ipfs-repo API

- package.json
- src/index.js
- test/browser.js
- test/ipld-git.js
- test/node.js
Depends on https://github.com/ipld/js-ipld-git/pull/1
> Add git resolver

- package.json
pull-defer is required [here](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L11) but was not declared in deps.
> added missing dep: pull-defer

- package.json
BREAKING CHANGE: All packages that depend on `ipld-resolver`
need to change their dependency.
Within your package that depends on `ipld-resolver` do:
npm uninstall ipld-resolver
npm intall ipld
Then search for all imports of `ipld-resolver` and change from
const IPLDResolver = require('ipld-resolver')
to
const Ipld = require('ipld')
Closes #116.
> chore: Rename package from `ipld-resolver` to `ipld`

- src/index.js
- test/basics.js
I also made the message more informative because we lose the stack trace with `setImmediate`.
> fix: handle required options for IPLDResolver.put

- package.json
The metadata for npm was still pointing to `js-ipld-resolver` instead
of just `js-ipld`.
> chore: fix repository links

- src/index.js
When bundling a web app that depends on js-ipfs with [parcel](https://parceljs.org/) I get this error msg.
```js
es6.promise.js:110 Unhandled promise rejection Error: dag-cboralready supported
at Object.IPLDResolver.support.add (index.js:48)
at new IPLDResolver (index.js:72)
at new IPFS (index.js:72)
```
This PR just fixes the formatting of the error message (**dag-cboralready supported**) and brings it more in line with the tone of the other error messages in the file.
I'm going to dig around and raise a separate issue for the cause of the error.
> Fix "resolver exists" error message

- test/ipld-zcash.js
The Zcash tests were broken due to a change in the underlying
js-ipld-zcash library.
> fix: Zcash tests were broken

- src/index.js
The require time profile for starting an IPFS daemon (`ipfs daemon`) showed IPLD as a significant contributor to the total time spent requiring modules. This is because the formats are all required ahead of time:
In the trace above, you can see the IPLD dependency taking 386ms in total of require time. Of which, the default IPLD formats take around 200ms of time to require. You can see `ipld-bitcoin`, `ipld-ethereum` and `ipld-zcash` taking the majority of that time.
This PR adds support for these default modules lazily. You only suffer the require time when you use a particular format. So if you never use git, ethereum or zcash blocks (probably most people right now) they don't contribute to the startup time of your node.
Now IPLD takes 121ms to require.
> perf: lazy load format resolvers

- README.md
- src/index.js
- test/basics.js
- test/ipld-bitcoin.js
- test/ipld-dag-cbor.js
- test/ipld-dag-pb.js
- test/ipld-eth-block.js
- test/ipld-eth.js
- test/ipld-git.js
- test/ipld-zcash.js
BREAKING CHANGE:
The IPLD constructor is no longer taking a BlockService as its
only parameter, but an objects object with `blockService` as a
key.
You need to upgrade your code if you initialize IPLD.
Prior to this change:
```js
const ipld = new Ipld(blockService)
```
Now:
```js
const ipld = new Ipld({blockService: blockService})
```
> refactor: make blockService an option parameter

- README.md
- package.json
- src/index.js
- test/ipld-bitcoin.js
- test/ipld-eth-block.js
- test/ipld-eth.js
- test/ipld-git.js
- test/ipld-zcash.js
Instead of having IPLD using all currently available [IPLD Format]
implementations automatically, pass the Formats that should be
used into the constructor as options.
This will also decrease the bundle size as every user of IPLD can
decide which IPLD Formats should be used. By default
[ipld-dag-cbor] and [ipld-dag-pb] are used as those are the ones
also heavily used within the IPFS ecosystem.
BREAKING CHANGE: Not all IPLD Formats are included by default
By default only the [ipld-dag-cbor] and [ipld-dag-pb] [IPLD Format]s
are included. If you want to use other IPLD Formats you need
to pass them into the constructor.
The code to restore the old behaviour could look like this:
```js
const ipldDagPb = require('ipld-dag-pb')
const ipldDagCbor = require('ipld-dag-cbor')
const ipldGit = …
```
> refactor: pass in IPLD Formats into the constructor

- README.md
Tracis and CircleCI are no longer used, the node and npm batches
were outdate.
> docs: remove outdated badges

- OKR.md
Ref: https://github.com/ipfs/pm/issues/698
- [2018 Q3 Retrospective Document](https://docs.google.com/document/d/1ITVW5yysj0bZiluEKasQ57edpNwOZ-P5GQGgoclwQno/edit#heading=h.906pmio05dzr). Please complete this ASAP.
- [2018 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1Lfd91hi3nFlLRS1r-FHvK2ip2Ll6ukraufCgepw43bw/edit#gid=754421585)
@vmx et al, you know the drill :)
> 2018 Q4 OKR Planning

- package.json
- test/ipld-eth.js
The eth-hash-to-cid is a module that is no longer used by any
project. Hence replace it with two simple lines of code.
> refactor: remove eth-hash-to-cid module

- README.md
- src/index.js
- test/ipld-all.js
IPLD and it's resolvers are the gatekeepers of creating CIDs from nodes. IPFS has variations on `onlyHash` parameters that can be passed to CLI commands, the intention of which is to return a CID for a given node and not write it to a block store.
Since IPLD guards the block store and the generation of CIDs, we have to reach deep into it's heart to peform this. It makes sense that this should occur further down the stack so this PR adds an `onlyHash` option to `ipld.put` to accomplish this.
> feat: adds onlyHash option to ipld.put

- src/index.js
No need to get the block if we're not going to be able to resolve a path within it.
License: MIT
Signed-off-by: Alan Shaw <alan.shaw@protocol.ai>
> perf: fail fast for missing format

- README.md
- src/index.js
- test/ipld-all.js
With `getMany()` it's possible to get several blocks with one call.
Closes #132.
> feature: add getMany()

- README.md
- src/index.js
- test/browser.js
- test/format-support.js
- test/node.js
This backwards compatible PR allows missing IPLD formats to be loaded dynamically.
This follows on from the discussion here https://github.com/ipld/js-ipld/pull/164#discussion_r228121092
A new constructor option `loadFormat` allows users to asynchronously load an IPLD format. The IPLD instance will call this function automatically when it is requested to resolve a format that it doesn't currently understand.
This can re-enable lazy loading for IPLD modules in IPFS and also means that people who just want to add _more_ resolvers can do so without having to depend directly on the defaults and pass them in as well.
It also removes a bunch of repeated "No resolver found for codec" blocks so the code is more DRYFTW \o/
> feat: dynamic format loading

- package.json
- test/ipld-dag-pb.js
**BREAKING CHANGE:**
DAGNodes no longer have `.cid` or `.multihash` properties - see ipld/js-ipld-dag-pb#99 for more and and https://github.com/ipld/js-ipld/issues/173 for the performance win.
Follows on from ipld/js-ipld-dag-pb#99 and updates this module to not rely on DAGNodes having knowledge of their CIDs.
Fixes the tests which could use a closer look at, for example they overwrite the value of `node3` twice.
> fix: updates ipld-dag-pb dep to version without .cid or .multihash properties

- README.md
- src/index.js
- test/ipld-dag-cbor.js
- test/ipld-dag-pb.js
We can pass a path to `ipld.get` that makes the resolver attempt to do a graph traversal until it runs out of path segments to resolve.
At that point we don't know the `cid` of the node that will be returned, which things like the `unixfs-exporter` need to know.
> feat: return cid of last node traversed from ipld.get and friends

- package.json
- src/index.js
- test/basics.js
- test/ipld-dag-cbor.js
- test/ipld-dag-pb.js
- test/ipld-git.js
With the AEgir 17.1.1 release StandardJS 12 was introduced, which lead
to new linting rules. Those rules made the linting fail. This commit
fixes those issues and also upgrades AEgir to 17.1.1 explicitly.
> fix: linting passes again

- package.json
- src/index.js
- test/basics.js
- test/ipld-all.js
This removes the dependency on `ipfs-repo`, `ipfs-block-service` and `interface-datastore` and resolves #151.
BTW the current implementation has a bug where the `keys` backend is stored on disk and not in memory. I [added it here](https://github.com/alanshaw/ipld-in-memory/blob/01b86380ebec95248d090a5a0ae95141bcc4067c/index.js#L18), compare with [the current backends](https://github.com/ipld/js-ipld/blob/f7494ec7b7a52a34d33d8ec308718b31919e08b6/src/index.js#L438-L440)...so definitely worth switching ;)
BREAKING CHANGE: This module no longer exports an `inMemory` utility to create an IPLD instance that uses a block service that stores data in memory. Please use the [`ipld-in-memory`](https://www.npmjs.com/package/ipld-in-memory) module instead.
> refactor: remove inMemory util

- .gitattributes
- .travis.yml
- README.md
- ci/Jenkinsfile
- package.json
Jenkins is no longer a thing, hence enable Travis.
> chore: enable Travis for CI

- README.md
The whole IPLD APIs get a review to make them more consistent and
easier to use.
Changes to compared to the current spec:
- No more callbacks, everything is Promises.
- `get()`:
- Is renamed to `resolve()` to indicate that it also takes a mandatory
path argument.
- Doesn’t have a `cid` in the return value anymore. That use case is
covered by returning all objects that were traversed. Their `value`
will always be the CID of the next one to traverse. So if you want
to know the CID of the current IPLD Node, just look at the `value`
of the previously returned IPLD Node.
- Doesn’t return a single value, but an iterator.
- `localResolve` option is removed. If you want to resolve a single IPLD
Node only, just stop the iterator after the first item.
- `getStream()` is removed without replacement. …
> docs: major API changes

- src/index.js
- test/ipld-dag-pb.js
The [interface-ipld-format spec](https://github.com/ipld/interface-ipld-format#utilcidbinaryblob-options) says the CID verison option is `cidVersion`.  This module passes it to formats as `version` which is subsequently ignored.
Since `ipld-dag-pb` now defaults to V1 CIDs this results in incorrect CIDs being generated if you request V0 CIDs.
> fix: respect the `cidVersion` option

- package.json
- src/index.js
- test/basics.js
- test/browser.js
- test/ipld-all.js
- test/node.js
There's no need for the promisify-es6 module anymore as all the code
is using async/await based libraries now.
> refactor: make code promisify free

- test/node.js
I'm pretty sure this has nothing to do with the flaky Windows tests but I noticed it while testing on Windows. String concatenation is a no-no for building cross-platform and safe paths, and there's a `fs.mkdtemp()` these days to do the work of making a safe temp dir.
> fix: minor improvement to path handling in Node.js tests

- README.md
- package.json
- src/index.js
- test/basics.js
This is so the user can signal that they are no longer interested in the results of the operation and system components can stop trying to fulfil it.
> feat: support passing AbortSignal instances to the configured blockservice

- package.json
- test/ipld-bitcoin.spec.js
`multihash.decode` returns Uint8Arrays which we set as `prevHash`
but bitcoin-lib requires these to be node Buffers.
> fix: create buffers from decoded multihash digests

- README.md
- src/index.js
It's useful to be able to get the format implementations out of ipld
just before `ipld.put` operations in the HTTP API server of IPFS.
This is because we've serialized the node on the client for transmission
over HTTP so need to deserialize it before passing it into `ipld.put`
for it to be serialized (and as such, verified) again.
We can duplicate the list of resolvers and logic behind the addition
of new resolvers from ipld or we can just expose the `getFormat` function
which we do here to reduce any code duplication.
> feat: expose getFormat function

- src/index.js
- test/format-support.spec.js
The right property is `.codec` and not `.format`.
Adds a test for the same and also runs the custom format tests again.
> fix: use correct property when checking if resolver exists

- README.md
`ipfs-repo` is now using async/await, update the usage example in the
README accordingly.
Closes #289.
> docs: fix README usage example
